[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_VNC_SCREEN)s +extension RANDR
user=chrome
autorestart=true
priority=100

[program:chrome]
environment=HOME="/home/chrome",DISPLAY=":1",USER="chrome"
command=/bin/bash -c 'rm -rf /tmp/chrome_user_data_dir && /opt/google/chrome/chrome --window-size=%(ENV_CHROME_WINDOW_SIZE)s %(ENV_CHROME_OPTS)s'
user=chrome
autorestart=true
priority=200

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 %(ENV_X11VNC_AUTH)s -wait 5 -forever -xrandr
user=chrome
autorestart=true
priority=300

[program:socat]
command=/usr/bin/socat -v tcp-listen:9222,reuseaddr,fork tcp:localhost:9922
user=chrome
autorestart=true
priority=999
stdout_logfile=/tmp/socat.log
stderr_logfile=/tmp/socat.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=0
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=0

[program:chrome-watchdog]
command=/bin/bash /watchdog.sh
user=chrome
autorestart=true
priority=25